using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace HIS.Desktop.Plugins.RegisterExamKiosk.ADO
{
    public class ServiceADO : MOS.EFMODEL.DataModels.V_HIS_SERVICE
    {
        public ServiceADO(MOS.EFMODEL.DataModels.V_HIS_SERVICE service, decimal? PriceService)
        {
            this.ACTIVE_INGR_BHYT_CODE = service.ACTIVE_INGR_BHYT_CODE;
            this.ACTIVE_INGR_BHYT_NAME = service.ACTIVE_INGR_BHYT_NAME;
            this.AGE_FROM = service.AGE_FROM;
            this.AGE_TO = service.AGE_TO;
            this.ALLOW_SEND_PACS = service.ALLOW_SEND_PACS;
            this.ALLOW_SIMULTANEITY = service.ALLOW_SIMULTANEITY;
            this.APPLIED_PATIENT_CLASSIFY_IDS = service.APPLIED_PATIENT_CLASSIFY_IDS;
            this.APPLIED_PATIENT_TYPE_IDS = service.APPLIED_PATIENT_TYPE_IDS;
            this.APP_CREATOR = service.APP_CREATOR;
            this.APP_MODIFIER = service.APP_MODIFIER;
            this.ATTACH_ASSIGN_PRINT_TYPE_CODE = service.ATTACH_ASSIGN_PRINT_TYPE_CODE;
            this.BHYT_WHITELIST_CODES = service.BHYT_WHITELIST_CODES;
            this.BILL_OPTION = service.BILL_OPTION;
            this.BILL_PATIENT_TYPE_ID = service.BILL_PATIENT_TYPE_ID;
            this.BODY_PART_IDS = service.BODY_PART_IDS;
            this.CAPACITY = service.CAPACITY;
            this.COGS = service.COGS;
            this.CONCENTRA = service.CONCENTRA;
            this.CREATE_TIME = service.CREATE_TIME;
            this.CREATOR = service.CREATOR;
            this.DEFAULT_PATIENT_TYPE_ID = service.DEFAULT_PATIENT_TYPE_ID;
            this.DESCRIPTION = service.DESCRIPTION;
            this.DIIM_TYPE_CODE = service.DIIM_TYPE_CODE;
            this.DIIM_TYPE_ID = service.DIIM_TYPE_ID;
            this.DIIM_TYPE_NAME = service.DIIM_TYPE_NAME;
            this.DO_NOT_USE_BHYT = service.DO_NOT_USE_BHYT;
            //this.DO_NOT_USE_BHYT_IN_EXAM = service.DO_NOT_USE_BHYT_IN_EXAM;
            this.ESTIMATE_DURATION = service.ESTIMATE_DURATION;
            this.EXE_SERVICE_MODULE_ID = service.EXE_SERVICE_MODULE_ID;
            this.FILM_SIZE_ID = service.FILM_SIZE_ID;
            this.FUEX_TYPE_CODE = service.FUEX_TYPE_CODE;
            this.FUEX_TYPE_ID = service.FUEX_TYPE_ID;
            this.FUEX_TYPE_NAME = service.FUEX_TYPE_NAME;
            this.GENDER_ID = service.GENDER_ID;
            this.GROUP_CODE = service.GROUP_CODE;
            this.HEIN_LIMIT_PRICE = service.HEIN_LIMIT_PRICE;
            this.HEIN_LIMIT_PRICE_INTR_TIME = service.HEIN_LIMIT_PRICE_INTR_TIME;
            this.HEIN_LIMIT_PRICE_IN_TIME = service.HEIN_LIMIT_PRICE_IN_TIME;
            this.HEIN_LIMIT_PRICE_OLD = service.HEIN_LIMIT_PRICE_OLD;
            this.HEIN_LIMIT_RATIO = service.HEIN_LIMIT_RATIO;
            this.HEIN_LIMIT_RATIO_OLD = service.HEIN_LIMIT_RATIO_OLD;
            this.HEIN_ORDER = service.HEIN_ORDER;
            this.HEIN_SERVICE_BHYT_CODE = service.HEIN_SERVICE_BHYT_CODE;
            this.HEIN_SERVICE_BHYT_NAME = service.HEIN_SERVICE_BHYT_NAME;
            this.HEIN_SERVICE_TYPE_BHYT_CODE = service.HEIN_SERVICE_TYPE_BHYT_CODE;
            this.HEIN_SERVICE_TYPE_CODE = service.HEIN_SERVICE_TYPE_CODE;
            this.HEIN_SERVICE_TYPE_ID = service.HEIN_SERVICE_TYPE_ID;
            this.HEIN_SERVICE_TYPE_NAME = service.HEIN_SERVICE_TYPE_NAME;
            this.HEIN_SERVICE_TYPE_NUM_ORDER = service.HEIN_SERVICE_TYPE_NUM_ORDER;
            this.ICD_CM_ID = service.ICD_CM_ID;
            this.ID = service.ID;
            this.IS_ACTIVE = service.IS_ACTIVE;
            this.IS_ALLOW_EXPEND = service.IS_ALLOW_EXPEND;
            this.IS_ANTIBIOTIC_RESISTANCE = service.IS_ANTIBIOTIC_RESISTANCE;
            this.IS_AUTO_EXPEND = service.IS_AUTO_EXPEND;
            this.IS_AUTO_FINISH = service.IS_AUTO_FINISH;
            this.IS_AUTO_SPLIT_REQ = service.IS_AUTO_SPLIT_REQ;
            this.IS_BLOCK_DEPARTMENT_TRAN = service.IS_BLOCK_DEPARTMENT_TRAN;
            this.IS_CONDITIONED = service.IS_CONDITIONED;
            this.IS_DELETE = service.IS_DELETE;
            this.IS_DISALLOWANCE_NO_EXECUTE = service.IS_DISALLOWANCE_NO_EXECUTE;
            this.IS_ENABLE_ASSIGN_PRICE = service.IS_ENABLE_ASSIGN_PRICE;
            this.IS_KIDNEY = service.IS_KIDNEY;
            this.IS_LEAF = service.IS_LEAF;
            this.IS_MULTI_REQUEST = service.IS_MULTI_REQUEST;
            this.IS_NOT_CHANGE_BILL_PATY = service.IS_NOT_CHANGE_BILL_PATY;
            this.IS_NOT_REQUIRED_COMPLETE = service.IS_NOT_REQUIRED_COMPLETE;
            this.IS_NOT_SHOW_TRACKING = service.IS_NOT_SHOW_TRACKING;
            this.IS_NO_HEIN_LIMIT_FOR_SPECIAL = service.IS_NO_HEIN_LIMIT_FOR_SPECIAL;
            this.IS_OTHER_SOURCE_PAID = service.IS_OTHER_SOURCE_PAID;
            this.IS_OUT_OF_DRG = service.IS_OUT_OF_DRG;
            this.IS_OUT_OF_MANAGEMENT = service.IS_OUT_OF_MANAGEMENT;
            this.IS_OUT_PARENT_FEE = service.IS_OUT_PARENT_FEE;
            this.IS_REQUIRED_SAMPLE_TYPE = service.IS_REQUIRED_SAMPLE_TYPE;
            this.IS_SPECIFIC_HEIN_PRICE = service.IS_SPECIFIC_HEIN_PRICE;
            this.IS_SPLIT_REQ_BY_SAMPLE_TYPE = service.IS_SPLIT_REQ_BY_SAMPLE_TYPE;
            this.IS_SPLIT_SERVICE = service.IS_SPLIT_SERVICE;
            this.IS_SPLIT_SERVICE_REQ = service.IS_SPLIT_SERVICE_REQ;
            this.IS_USE_SERVICE_HEIN = service.IS_USE_SERVICE_HEIN;
            this.IS_VACCINE = service.IS_VACCINE;
            this.MAX_AMOUNT = service.MAX_AMOUNT;
            this.MAX_EXPEND = service.MAX_EXPEND;
            this.MAX_PROCESS_TIME = service.MAX_PROCESS_TIME;
            this.MAX_PROC_TIME_EXCEPT_PATY_IDS = service.MAX_PROC_TIME_EXCEPT_PATY_IDS;
            this.MAX_TOTAL_PROCESS_TIME = service.MAX_TOTAL_PROCESS_TIME;
            this.MIN_DURATION = service.MIN_DURATION;
            this.MIN_PROCESS_TIME = service.MIN_PROCESS_TIME;
            this.MIN_PROC_TIME_EXCEPT_PATY_IDS = service.MIN_PROC_TIME_EXCEPT_PATY_IDS;
            this.MODIFIER = service.MODIFIER;
            this.MODIFY_TIME = service.MODIFY_TIME;
            this.MUST_BE_CONSULTED = service.MUST_BE_CONSULTED;
            this.NOTICE = service.NOTICE;
            this.NUMBER_OF_FILM = service.NUMBER_OF_FILM;
            this.NUM_ORDER = service.NUM_ORDER;
            this.OTHER_PAY_SOURCE_ICDS = service.OTHER_PAY_SOURCE_ICDS;
            this.OTHER_PAY_SOURCE_ID = service.OTHER_PAY_SOURCE_ID;
            this.PACKAGE_ID = service.PACKAGE_ID;
            this.PACKAGE_PRICE = service.PACKAGE_PRICE;
            this.PACS_TYPE_CODE = service.PACS_TYPE_CODE;
            this.PARENT_ID = service.PARENT_ID;
            this.PETROLEUM_CODE = service.PETROLEUM_CODE;
            this.PETROLEUM_NAME = service.PETROLEUM_NAME;
            this.PROCESS_CODE = service.PROCESS_CODE;
            this.PTTT_GROUP_CODE = service.PTTT_GROUP_CODE;
            this.PTTT_GROUP_ID = service.PTTT_GROUP_ID;
            this.PTTT_GROUP_NAME = service.PTTT_GROUP_NAME;
            this.PTTT_METHOD_ID = service.PTTT_METHOD_ID;
            this.RATION_GROUP_ID = service.RATION_GROUP_ID;
            this.RATION_SYMBOL = service.RATION_SYMBOL;
            this.REVENUE_DEPARTMENT_ID = service.REVENUE_DEPARTMENT_ID;
            this.SAMPLE_TYPE_CODE = service.SAMPLE_TYPE_CODE;
            this.SERVICE_CODE = service.SERVICE_CODE;
            this.SERVICE_NAME = service.SERVICE_NAME;
            this.SERVICE_TYPE_CODE = service.SERVICE_TYPE_CODE;
            this.SERVICE_TYPE_ID = service.SERVICE_TYPE_ID;
            this.SERVICE_TYPE_NAME = service.SERVICE_TYPE_NAME;
            this.SERVICE_UNIT_CODE = service.SERVICE_UNIT_CODE;
            this.SERVICE_UNIT_ID = service.SERVICE_UNIT_ID;
            this.SERVICE_UNIT_NAME = service.SERVICE_UNIT_NAME;
            this.SETY_EXE_SERVICE_MODULE_ID = service.SETY_EXE_SERVICE_MODULE_ID;
            this.SPECIALITY_CODE = service.SPECIALITY_CODE;
            this.SUIM_INDEX_CODE = service.SUIM_INDEX_CODE;
            this.SUIM_INDEX_ID = service.SUIM_INDEX_ID;
            this.SUIM_INDEX_NAME = service.SUIM_INDEX_NAME;
            this.TAX_RATE_TYPE = service.TAX_RATE_TYPE;
            this.TESTING_TECHNIQUE = service.TESTING_TECHNIQUE;
            this.TEST_COVID_TYPE = service.TEST_COVID_TYPE;
            this.TEST_TYPE_CODE = service.TEST_TYPE_CODE;
            this.TEST_TYPE_ID = service.TEST_TYPE_ID;
            this.TEST_TYPE_NAME = service.TEST_TYPE_NAME;
            this.TOTAL_TIME_EXCEPT_PATY_IDS = service.TOTAL_TIME_EXCEPT_PATY_IDS;
            this.WARNING_SAMPLING_TIME = service.WARNING_SAMPLING_TIME;
            this.PRICE = PriceService;
        }
        public decimal? PRICE { get; set; }
    }
}
