namespace HIS.Desktop.Plugins.Library.ElectronicBill.Config
{
	public class SdaConfigKey
	{
		public const string ACCOUNT_CONFIG_KEY = "CONFIG_KEY__HIS_DESKTOP__ELECTRONIC_BILL__ACCOUNT";

		public const string ACCOUNT_CONFIG_KEY__BKAV = "CONFIG_KEY__HIS_DESKTOP__ELECTRONIC_BILL__ACCOUNT__BKAV";

		public const string ACCOUNT_CONFIG_KEY__VIETEL = "CONFIG_KEY__HIS_DESKTOP__ELECTRONIC_BILL__ACCOUNT__VIETEL";

		public const string ACCOUNT_CONFIG_KEY__VNPT = "CONFIG_KEY__HIS_DESKTOP__ELECTRONIC_BILL__ACCOUNT__VNPT";

		public const string ACCOUNT_CONFIG_KEY__MOBIFONE = "CONFIG_KEY__HIS_DESKTOP__ELECTRONIC_BILL__ACCOUNT__MOBIFONE";

		public const string ACCOUNT_CONFIG_KEY__CYBERBILL = "CONFIG_KEY__HIS_DESKTOP__ELECTRONIC_BILL__ACCOUNT__CYBERBILL";

		public const string ACCOUNT_CONFIG_KEY__SOFTDREAM = "CONFIG_KEY__HIS_DESKTOP__ELECTRONIC_BILL__ACCOUNT__SOFTDREAM";

		public const string ACCOUNT_CONFIG_KEY__MINVOICE = "CONFIG_KEY__HIS_DESKTOP__ELECTRONIC_BILL__ACCOUNT__MINVOICE";

		public const string ACCOUNT_CONFIG_KEY__VNINVOICE = "CONFIG_KEY__HIS_DESKTOP__ELECTRONIC_BILL__ACCOUNT__VNINVOICE";
	}
}
