//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventec.Common.SignFile.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Inventec.Common.SignFile.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;xsd:schema targetNamespace=&quot;http://uri.etsi.org/01903/v1.3.2#&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns=&quot;http://uri.etsi.org/01903/v1.3.2#&quot; xmlns:ds=&quot;http://www.w3.org/2000/09/xmldsig#&quot; elementFormDefault=&quot;qualified&quot;&gt;
        ///	&lt;xsd:import namespace=&quot;http://www.w3.org/2000/09/xmldsig#&quot; schemaLocation=&quot;http://www.w3.org/TR/2002/REC-xmldsig-core-20020212/xmldsig-core-schema.xsd&quot;/&gt;
        ///	&lt;!-- Start auxiliary types definitions: AnyType, ObjectIdentifierType, 
        ///Encapsulated [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string XAdES_1_3_2 {
            get {
                return ResourceManager.GetString("XAdES_1_3_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;!DOCTYPE schema
        ///  PUBLIC &quot;-//W3C//DTD XMLSchema 200102//EN&quot; &quot;http://www.w3.org/2001/XMLSchema.dtd&quot;
        /// [
        ///   &lt;!ATTLIST schema 
        ///     xmlns:ds CDATA #FIXED &quot;http://www.w3.org/2000/09/xmldsig#&quot;&gt;
        ///   &lt;!ENTITY dsig &apos;http://www.w3.org/2000/09/xmldsig#&apos;&gt;
        ///   &lt;!ENTITY % p &apos;&apos;&gt;
        ///   &lt;!ENTITY % s &apos;&apos;&gt;
        ///  ]&gt;
        ///
        ///&lt;!-- Schema for XML Signatures
        ///    http://www.w3.org/2000/09/xmldsig#
        ///    $Revision: 1.1 $ on $Date: 2002/02/08 20:32:26 $ by $Author: reagle $
        ///
        ///    Copyright 2001 The Internet Societ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string xmldsig_core_schema {
            get {
                return ResourceManager.GetString("xmldsig_core_schema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!-- DTD for XML Schemas: Part 1: Structures
        ///     Public Identifier: &quot;-//W3C//DTD XMLSCHEMA 200102//EN&quot;
        ///     Official Location: http://www.w3.org/2001/XMLSchema.dtd --&gt;
        ///&lt;!-- $Id: XMLSchema.dtd,v 1.31 2001/10/24 15:50:16 ht Exp $ --&gt;
        ///&lt;!-- Note this DTD is NOT normative, or even definitive. --&gt;           &lt;!--d--&gt;
        ///&lt;!-- prose copy in the structures REC is the definitive version --&gt;    &lt;!--d--&gt;
        ///&lt;!-- (which shouldn&apos;t differ from this one except for this --&gt;         &lt;!--d--&gt;
        ///&lt;!-- comment and entity expansio [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string XMLSchema {
            get {
                return ResourceManager.GetString("XMLSchema", resourceCulture);
            }
        }
    }
}
