//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventec.Common.SignLibrary.LibraryMessage {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MessageViResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessageViResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Inventec.Common.SignLibrary.LibraryMessage.MessageViResource", typeof(MessageViResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có muốn mở file vừa ký.
        /// </summary>
        internal static string BanCoMuonMoFileVuaKy {
            get {
                return ResourceManager.GetString("BanCoMuonMoFileVuaKy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có muốn tạo thêm luồng ký để thực hiện các bước tiếp theo.
        /// </summary>
        internal static string BanCoMuonTaoThemLuongKy {
            get {
                return ResourceManager.GetString("BanCoMuonTaoThemLuongKy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn không thể thực hiện ký tại trang ký. Vui lòng chọn ký từ trang thứ 2 trở đi..
        /// </summary>
        internal static string BanKhongTheThucHienKyTaiTrangKyVuiLongChonKyTuTrangThu2TroDi {
            get {
                return ResourceManager.GetString("BanKhongTheThucHienKyTaiTrangKyVuiLongChonKyTuTrangThu2TroDi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bệnh nhân chưa có được phát hành thẻ thông minh.
        /// </summary>
        internal static string BenhNhanChuaCoTheThongMinh {
            get {
                return ResourceManager.GetString("BenhNhanChuaCoTheThongMinh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bệnh nhân {0} đã có trong luồng ký.
        /// </summary>
        internal static string BenhNhanDaCoTrongLuongKy {
            get {
                return ResourceManager.GetString("BenhNhanDaCoTrongLuongKy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bệnh nhân không có số thẻ KCB..
        /// </summary>
        internal static string BenhNhanKhongCoTheKCB {
            get {
                return ResourceManager.GetString("BenhNhanKhongCoTheKCB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bệnh nhân {0} không có trong luồng ký.
        /// </summary>
        internal static string BenhNhanKhongCoTrongLuongKy {
            get {
                return ResourceManager.GetString("BenhNhanKhongCoTrongLuongKy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bệnh nhân {0} không phải người ký tiếp theo, vui lòng kiểm tra lại thông tin.
        /// </summary>
        internal static string BenhNhanKhongPhaiNguoiKyTiepTheoVuiLongKiemTraLai {
            get {
                return ResourceManager.GetString("BenhNhanKhongPhaiNguoiKyTiepTheoVuiLongKiemTraLai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chưa kết nối thiết bị.
        /// </summary>
        internal static string BugCode40 {
            get {
                return ResourceManager.GetString("BugCode40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số thẻ không chinh xác.
        /// </summary>
        internal static string BugCode41 {
            get {
                return ResourceManager.GetString("BugCode41", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số thẻ không chính xác.
        /// </summary>
        internal static string BugCode42 {
            get {
                return ResourceManager.GetString("BugCode42", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số thẻ không chính xác.
        /// </summary>
        internal static string BugCode43 {
            get {
                return ResourceManager.GetString("BugCode43", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chủ thẻ chưa có vân tay.
        /// </summary>
        internal static string BugCode44 {
            get {
                return ResourceManager.GetString("BugCode44", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vân tay không hợp lệ.
        /// </summary>
        internal static string BugCode45 {
            get {
                return ResourceManager.GetString("BugCode45", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thiết bị không đọc được thông tin thẻ.
        /// </summary>
        internal static string BugCode46 {
            get {
                return ResourceManager.GetString("BugCode46", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thẻ không hợp lệ.
        /// </summary>
        internal static string BugCode47 {
            get {
                return ResourceManager.GetString("BugCode47", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quá thời gian tap thẻ.
        /// </summary>
        internal static string BugCode48 {
            get {
                return ResourceManager.GetString("BugCode48", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thiết bị không đọc được thông tin thẻ.
        /// </summary>
        internal static string BugCode49 {
            get {
                return ResourceManager.GetString("BugCode49", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi không xác định (exception).
        /// </summary>
        internal static string BugCode99 {
            get {
                return ResourceManager.GetString("BugCode99", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chưa chọn mối quan hệ chủ thẻ với bệnh nhân.
        /// </summary>
        internal static string ChuaChonMoiQuanHeVoiBenhNhan {
            get {
                return ResourceManager.GetString("ChuaChonMoiQuanHeVoiBenhNhan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} đã ký {1}.
        /// </summary>
        internal static string ChuKyDienTuBenhNhanDaKy {
            get {
                return ResourceManager.GetString("ChuKyDienTuBenhNhanDaKy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có sự cố khi xem văn bản đã ký của bệnh nhân.
        /// </summary>
        internal static string CoSuCoKhiTaiFileDaKyCuaBenhNhan {
            get {
                return ResourceManager.GetString("CoSuCoKhiTaiFileDaKyCuaBenhNhan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có sự cố xảy ra, vui lòng kiểm tra lại thông tin hoặc liên hệ với quản trị hệ thống để được hỗ trợ.
        /// </summary>
        internal static string CoSuCoXayRaVuiLongKiemTraLaiHoacLienHeVoiQuanTriHeThongDeDuocHoTro {
            get {
                return ResourceManager.GetString("CoSuCoXayRaVuiLongKiemTraLaiHoacLienHeVoiQuanTriHeThongDeDuocHoTro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dữ liệu không hợp lệ.
        /// </summary>
        internal static string DuLieuKhongHopLe {
            get {
                return ResourceManager.GetString("DuLieuKhongHopLe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gửi văn bản lên hệ thống EMR thất bại..
        /// </summary>
        internal static string GuiVanBanLenHeThongEMRThatBai {
            get {
                return ResourceManager.GetString("GuiVanBanLenHeThongEMRThatBai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không nhập quan hệ của người nhà ký.
        /// </summary>
        internal static string KhongNhapTTDinhDanhHoacChonTheKy {
            get {
                return ResourceManager.GetString("KhongNhapTTDinhDanhHoacChonTheKy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy chữ ký khi sử dụng thiết bị ký.
        /// </summary>
        internal static string KhongTimThayChuKyKhiSuDungBangKy {
            get {
                return ResourceManager.GetString("KhongTimThayChuKyKhiSuDungBangKy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy dữ liệu đã ký của bệnh nhân.
        /// </summary>
        internal static string KhongTimThayDuLieuDaKyCuaHoSo {
            get {
                return ResourceManager.GetString("KhongTimThayDuLieuDaKyCuaHoSo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy văn bản đã ký của bệnh nhân trên hệ thống quản lý file EMR.
        /// </summary>
        internal static string KhongTimThayFileDaKyCuaHoSoTrenHeThongFss {
            get {
                return ResourceManager.GetString("KhongTimThayFileDaKyCuaHoSoTrenHeThongFss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy file văn bản để in.
        /// </summary>
        internal static string KhongTimThayVanBanDeIn {
            get {
                return ResourceManager.GetString("KhongTimThayVanBanDeIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tồn tại văn bản để hủy ký, vui lòng kiểm tra lại.
        /// </summary>
        internal static string KhongTonTaiVanBanDeHuyKy {
            get {
                return ResourceManager.GetString("KhongTonTaiVanBanDeHuyKy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không xác định được dữ liệu để hủy ký.
        /// </summary>
        internal static string KhongXacDinhDuocDuLieuDeHuyKy {
            get {
                return ResourceManager.GetString("KhongXacDinhDuocDuLieuDeHuyKy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ký sử dụng USB token thất bại.
        /// </summary>
        internal static string KySuDungUSBTokenThatBai {
            get {
                return ResourceManager.GetString("KySuDungUSBTokenThatBai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ký văn bản phụ thuộc ({0} - {1}) thất bại. Không phải lượt ký của bản..
        /// </summary>
        internal static string KyVanBanPhuThocThatBai__KhongPhaiLuotKyCuaBan {
            get {
                return ResourceManager.GetString("KyVanBanPhuThocThatBai__KhongPhaiLuotKyCuaBan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi gọi service xác thực vân tay.
        /// </summary>
        internal static string LoiGoiServiceXacThucVanTay {
            get {
                return ResourceManager.GetString("LoiGoiServiceXacThucVanTay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã hồ sơ điều trị {0} không hợp lệ (Do chưa được đồng bộ từ phần mềm HIS sang hệ thống EMR).
        /// </summary>
        internal static string MaHoSoDieuTriKhongHopLe {
            get {
                return ResourceManager.GetString("MaHoSoDieuTriKhongHopLe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bắt buộc phải tạo luồng ký cho văn bản đã có trên hệ thống EMR sau đó mới có thể thực hiện ký..
        /// </summary>
        internal static string PhaiTaoLuongKyChoVanBanDaCoTrenHeThong {
            get {
                return ResourceManager.GetString("PhaiTaoLuongKyChoVanBanDaCoTrenHeThong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa trạng thái người dùng đã lưu tại máy trạm.
        /// </summary>
        internal static string ResetTrangThaiNguoiDungDaLuuTaiMayTram {
            get {
                return ResourceManager.GetString("ResetTrangThaiNguoiDungDaLuuTaiMayTram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản {0} chưa được tạo người ký trên hệ thống EMR, bạn có muốn thử lại với tài khoản khác?.
        /// </summary>
        internal static string TaiKhoanChuaDuocTaoNguoiKyTrenHeThongEMR {
            get {
                return ResourceManager.GetString("TaiKhoanChuaDuocTaoNguoiKyTrenHeThongEMR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản thiếu thông tin ảnh.
        /// </summary>
        internal static string TaiKhoanThieuThongTinAnh {
            get {
                return ResourceManager.GetString("TaiKhoanThieuThongTinAnh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản thiếu thông tin ảnh, bạn có muốn bỏ hiển thị ảnh chữ ký không?.
        /// </summary>
        internal static string TaiKhoanThieuThongTinAnhBanCoMuonBoHienThiAnh {
            get {
                return ResourceManager.GetString("TaiKhoanThieuThongTinAnhBanCoMuonBoHienThiAnh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản thiếu thông tin ảnh chữ ký. Hệ thống sẽ tự động cập nhật ảnh chữ ký theo thông tin chứng thư.
        /// </summary>
        internal static string TaiKhoanThieuThongTinAnhHeThongTuDongCapNhat {
            get {
                return ResourceManager.GetString("TaiKhoanThieuThongTinAnhHeThongTuDongCapNhat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông báo.
        /// </summary>
        internal static string ThongBao {
            get {
                return ResourceManager.GetString("ThongBao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tính năng chỉ giành cho bệnh án điện tử.
        /// </summary>
        internal static string TinhNangChiDanhChoBenhAnDienTu {
            get {
                return ResourceManager.GetString("TinhNangChiDanhChoBenhAnDienTu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tính năng chỉ giành cho bệnh án điện tử  (treatmentCode = {0}, documentName = {1}).
        /// </summary>
        internal static string TinhNangChiDanhChoBenhAnDienTuCoThamSo {
            get {
                return ResourceManager.GetString("TinhNangChiDanhChoBenhAnDienTuCoThamSo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tính năng ký sử dụng thiết bị ký chưa được hỗ trợ.
        /// </summary>
        internal static string TinhNangKySuDungBangKyChuaDuocHoTro {
            get {
                return ResourceManager.GetString("TinhNangKySuDungBangKyChuaDuocHoTro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tự động cập nhật ảnh chữ ký theo thông tin chứng thư thất bại.
        ///	Bạn có muốn tiếp tục ký và bỏ hiển thị ảnh chữ ký không?.
        /// </summary>
        internal static string TuDongCapNhatChuKyThatBaiBanCoMuonTiepTucVaBoHienThiChuKy {
            get {
                return ResourceManager.GetString("TuDongCapNhatChuKyThatBaiBanCoMuonTiepTucVaBoHienThiChuKy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Văn bản chưa được thiết lập nghiệp vụ ký.
        /// </summary>
        internal static string VanBanChuaDuocThietLapNghiepVuKy {
            get {
                return ResourceManager.GetString("VanBanChuaDuocThietLapNghiepVuKy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Văn bản có thể đã tồn tại trên hệ thống EMR. Bạn có chắc chắn thực hiện không?.
        /// </summary>
        internal static string VanBanCoTheDaTonTaiTrenHeThongEMRBanCoThucHienKhong {
            get {
                return ResourceManager.GetString("VanBanCoTheDaTonTaiTrenHeThongEMRBanCoThucHienKhong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vản bản đã tồn tại, không thể ký tiếp do hệ thống chặn(văn bản chỉ được ký 1 lần, văn bản đã trùng hiscode,...).
        /// </summary>
        internal static string VanBanDaTonTaiKhongTheKyTiepDoThietLapDangChan {
            get {
                return ResourceManager.GetString("VanBanDaTonTaiKhongTheKyTiepDoThietLapDangChan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vản bản đã tồn tại, phần mềm sẽ hiển thị văn bản cũ.
        /// </summary>
        internal static string VanBanDaTonTaiPhanMemSeHienThiVanBanCu {
            get {
                return ResourceManager.GetString("VanBanDaTonTaiPhanMemSeHienThiVanBanCu", resourceCulture);
            }
        }
    }
}
